// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/ble-tokens": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "現在ログインしているユーザーの新規 BLE トークンを発行する（24時間有効）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ble-tokens"
                ],
                "summary": "BLE トークン発行",
                "operationId": "createBleToken",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.BleTokenResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ble-tokens/current": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "現在ログインしているユーザーの有効な最新の BLE トークンを取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ble-tokens"
                ],
                "summary": "有効な BLE トークン取得",
                "operationId": "getCurrentBleToken",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.BleTokenResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/ble-tokens/{token}/user": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定した BLE トークンに紐づくユーザーの公開プロフィールを取得する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ble-tokens"
                ],
                "summary": "BLE トークンからユーザー情報取得",
                "operationId": "getUserByBleToken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "対象の BLE トークン",
                        "name": "token",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.BleTokenUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/lyrics": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "エンカウントをきっかけに歌詞チェーンへ1行を投稿する。チェーンが threshold に達すると楽曲生成ジョブが登録される。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lyrics"
                ],
                "summary": "歌詞投稿",
                "operationId": "postLyric",
                "parameters": [
                    {
                        "description": "歌詞投稿リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_request.PostLyricRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.PostLyricResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/lyrics/chains/{chain_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "チェーンの詳細と全歌詞エントリを返す。completed 時のみ song フィールドが含まれる。",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "lyrics"
                ],
                "summary": "歌詞チェーン詳細取得",
                "operationId": "getLyricChain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "チェーン ID",
                        "name": "chain_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.LyricChainDetailResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/music-connections/{provider}/authorize": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定プロバイダーの OAuth 認可フローを開始し authorize_url を返す",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "music-connections"
                ],
                "summary": "音楽サービス OAuth 認可 URL 取得",
                "operationId": "getMusicAuthorizeURL",
                "parameters": [
                    {
                        "type": "string",
                        "description": "spotify | apple_music",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.MusicAuthorizeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/music-connections/{provider}/callback": {
            "get": {
                "description": "OAuth コールバックを処理し、認可コードをトークンに交換してアプリへリダイレクト",
                "tags": [
                    "music-connections"
                ],
                "summary": "音楽サービス OAuth コールバック",
                "operationId": "handleMusicCallback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "spotify | apple_music",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "認可コード",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/api/v1/tracks/search": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Spotify Web API にプロキシするトラック検索",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tracks"
                ],
                "summary": "トラック検索",
                "operationId": "searchTracks",
                "parameters": [
                    {
                        "type": "string",
                        "description": "検索キーワード",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "件数（省略時20、最大50）",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "次ページカーソル",
                        "name": "cursor",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.TrackSearchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/tracks/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定トラックの詳細を返す（ID: \u003cprovider\u003e:track:\u003cexternal_id\u003e）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tracks"
                ],
                "summary": "トラック詳細取得",
                "operationId": "getTrack",
                "parameters": [
                    {
                        "type": "string",
                        "description": "トラック ID（例: spotify:track:123）",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.TrackDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Firebase 認証済みの新規ユーザーを登録する（初回ログイン時に一度だけ呼ぶ）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "ユーザー作成",
                "operationId": "createUser",
                "parameters": [
                    {
                        "description": "ユーザー作成リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_request.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザー自身のプロフィールを返す",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "自分のユーザー情報取得",
                "operationId": "getMe",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "DB レコードと Firebase アカウントを削除する（Firebase 削除はベストエフォート）",
                "tags": [
                    "users"
                ],
                "summary": "自分のアカウント削除",
                "operationId": "deleteMe",
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定したフィールドだけを部分更新する（null フィールドは変更しない）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "自分のプロフィール更新",
                "operationId": "patchMe",
                "parameters": [
                    {
                        "description": "プロフィール更新リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_request.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me/music-connections": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "自分の音楽サービス連携一覧を返す",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "music-connections"
                ],
                "summary": "音楽サービス連携一覧取得",
                "operationId": "getMyMusicConnections",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.MusicConnectionsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me/music-connections/{provider}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定プロバイダーの連携を解除する",
                "tags": [
                    "music-connections"
                ],
                "summary": "音楽サービス連携解除",
                "operationId": "deleteMyMusicConnection",
                "parameters": [
                    {
                        "type": "string",
                        "description": "spotify | apple_music",
                        "name": "provider",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me/push-tokens": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "device_id が既存なら更新して 200、新規なら 201 を返す",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "push-tokens"
                ],
                "summary": "プッシュトークン登録（upsert）",
                "operationId": "createPushToken",
                "parameters": [
                    {
                        "description": "プッシュトークン登録リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_request.CreatePushTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "既存デバイスを更新",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.DeviceResponse"
                        }
                    },
                    "201": {
                        "description": "新規デバイスを登録",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.DeviceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me/push-tokens/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定デバイスのレコードを削除する",
                "tags": [
                    "push-tokens"
                ],
                "summary": "プッシュトークン削除",
                "operationId": "deletePushToken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "デバイス ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定デバイスのトークン・有効フラグ・アプリバージョンを部分更新する",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "push-tokens"
                ],
                "summary": "プッシュトークン更新",
                "operationId": "patchPushToken",
                "parameters": [
                    {
                        "type": "string",
                        "description": "デバイス ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "プッシュトークン更新リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_request.UpdatePushTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.DeviceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/me/settings": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "認証中のユーザーのアプリ設定を返す",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "自分の設定取得",
                "operationId": "getMySettings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.SettingsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定したフィールドだけを部分更新する（null フィールドは変更しない）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "自分の設定更新",
                "operationId": "patchMySettings",
                "parameters": [
                    {
                        "description": "設定更新リクエスト",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_request.UpdateSettingsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.SettingsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "指定した ID の公開プロフィールを返す",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "他ユーザーのプロフィール取得",
                "operationId": "getUserByID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "対象ユーザー ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hackathon_internal_handler_schema_response.PublicUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.errorResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "サーバーが起動しているか確認する",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "ヘルスチェック",
                "operationId": "healthz",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/healthz/postgres": {
            "get": {
                "description": "PostgreSQL への接続を確認する（タイムアウト 5s）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "PostgreSQL ヘルスチェック",
                "operationId": "healthzPostgres",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "hackathon_internal_handler_schema_request.CreatePushTokenRequest": {
            "type": "object",
            "properties": {
                "app_version": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "platform": {
                    "type": "string",
                    "enum": [
                        "ios",
                        "android"
                    ]
                },
                "push_token": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_request.CreateUserRequest": {
            "type": "object",
            "properties": {
                "age_visibility": {
                    "type": "string",
                    "enum": [
                        "hidden",
                        "exact",
                        "by-10"
                    ]
                },
                "avatar_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "prefecture_id": {
                    "type": "string"
                },
                "sex": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female",
                        "other",
                        "no-answer"
                    ]
                }
            }
        },
        "hackathon_internal_handler_schema_request.PostLyricRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "encounter_id": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_request.UpdatePushTokenRequest": {
            "type": "object",
            "properties": {
                "app_version": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "push_token": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_request.UpdateSettingsRequest": {
            "type": "object",
            "properties": {
                "announcement_notification_enabled": {
                    "type": "boolean"
                },
                "batch_notification_enabled": {
                    "type": "boolean"
                },
                "ble_enabled": {
                    "type": "boolean"
                },
                "comment_notification_enabled": {
                    "type": "boolean"
                },
                "detection_distance": {
                    "type": "integer"
                },
                "encounter_notification_enabled": {
                    "type": "boolean"
                },
                "like_notification_enabled": {
                    "type": "boolean"
                },
                "location_enabled": {
                    "type": "boolean"
                },
                "notification_enabled": {
                    "type": "boolean"
                },
                "notification_frequency": {
                    "type": "string",
                    "enum": [
                        "immediate",
                        "hourly",
                        "daily"
                    ]
                },
                "profile_visible": {
                    "type": "boolean"
                },
                "schedule_enabled": {
                    "type": "boolean"
                },
                "schedule_end_time": {
                    "type": "string"
                },
                "schedule_start_time": {
                    "type": "string"
                },
                "theme_mode": {
                    "type": "string",
                    "enum": [
                        "light",
                        "dark",
                        "system"
                    ]
                },
                "track_visible": {
                    "type": "boolean"
                }
            }
        },
        "hackathon_internal_handler_schema_request.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "age_visibility": {
                    "type": "string",
                    "enum": [
                        "hidden",
                        "exact",
                        "by-10"
                    ]
                },
                "avatar_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "prefecture_id": {
                    "type": "string"
                },
                "sex": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female",
                        "other",
                        "no-answer"
                    ]
                }
            }
        },
        "hackathon_internal_handler_schema_response.BleToken": {
            "type": "object",
            "required": [
                "expires_at",
                "token"
            ],
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.BleTokenResponse": {
            "type": "object",
            "required": [
                "ble_token"
            ],
            "properties": {
                "ble_token": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.BleToken"
                }
            }
        },
        "hackathon_internal_handler_schema_response.BleTokenUser": {
            "type": "object",
            "required": [
                "display_name",
                "id"
            ],
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.BleTokenUserResponse": {
            "type": "object",
            "required": [
                "user"
            ],
            "properties": {
                "user": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.BleTokenUser"
                }
            }
        },
        "hackathon_internal_handler_schema_response.Device": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "enabled": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "platform": {
                    "type": "string",
                    "enum": [
                        "ios",
                        "android"
                    ]
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.DeviceResponse": {
            "type": "object",
            "properties": {
                "device": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.Device"
                }
            }
        },
        "hackathon_internal_handler_schema_response.GeneratedSongItem": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "duration_sec": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "mood": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.LyricChainDetailItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "participant_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "generating",
                        "completed",
                        "failed"
                    ]
                },
                "threshold": {
                    "type": "integer"
                }
            }
        },
        "hackathon_internal_handler_schema_response.LyricChainDetailResponse": {
            "type": "object",
            "properties": {
                "chain": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.LyricChainDetailItem"
                },
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hackathon_internal_handler_schema_response.LyricEntryWithUserItem"
                    }
                },
                "song": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.GeneratedSongItem"
                }
            }
        },
        "hackathon_internal_handler_schema_response.LyricChainItem": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "participant_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "pending",
                        "generating",
                        "completed",
                        "failed"
                    ]
                },
                "threshold": {
                    "type": "integer"
                }
            }
        },
        "hackathon_internal_handler_schema_response.LyricEntryItem": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "sequence_num": {
                    "type": "integer"
                }
            }
        },
        "hackathon_internal_handler_schema_response.LyricEntryWithUserItem": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "sequence_num": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.UserBrief"
                }
            }
        },
        "hackathon_internal_handler_schema_response.MusicAuthorizeResponse": {
            "type": "object",
            "properties": {
                "authorize_url": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.MusicConnectionItem": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "provider": {
                    "type": "string",
                    "enum": [
                        "spotify",
                        "apple_music"
                    ]
                },
                "provider_user_id": {
                    "type": "string"
                },
                "provider_username": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.MusicConnectionsResponse": {
            "type": "object",
            "properties": {
                "music_connections": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hackathon_internal_handler_schema_response.MusicConnectionItem"
                    }
                }
            }
        },
        "hackathon_internal_handler_schema_response.PaginationResult": {
            "type": "object",
            "properties": {
                "has_more": {
                    "type": "boolean"
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.PostLyricResponse": {
            "type": "object",
            "properties": {
                "chain": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.LyricChainItem"
                },
                "lyric_entry": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.LyricEntryItem"
                }
            }
        },
        "hackathon_internal_handler_schema_response.PublicTrack": {
            "type": "object",
            "properties": {
                "artist_name": {
                    "type": "string"
                },
                "artwork_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "preview_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.PublicUser": {
            "type": "object",
            "properties": {
                "age_range": {
                    "type": "string"
                },
                "avatar_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "birthplace": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "encounter_count": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "shared_track": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.PublicTrack"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.PublicUserResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.PublicUser"
                }
            }
        },
        "hackathon_internal_handler_schema_response.Settings": {
            "type": "object",
            "properties": {
                "announcement_notification_enabled": {
                    "type": "boolean"
                },
                "batch_notification_enabled": {
                    "type": "boolean"
                },
                "ble_enabled": {
                    "type": "boolean"
                },
                "comment_notification_enabled": {
                    "type": "boolean"
                },
                "detection_distance": {
                    "type": "integer"
                },
                "encounter_notification_enabled": {
                    "type": "boolean"
                },
                "like_notification_enabled": {
                    "type": "boolean"
                },
                "location_enabled": {
                    "type": "boolean"
                },
                "notification_enabled": {
                    "type": "boolean"
                },
                "notification_frequency": {
                    "type": "string",
                    "enum": [
                        "immediate",
                        "hourly",
                        "daily"
                    ]
                },
                "profile_visible": {
                    "type": "boolean"
                },
                "schedule_enabled": {
                    "type": "boolean"
                },
                "schedule_end_time": {
                    "type": "string"
                },
                "schedule_start_time": {
                    "type": "string"
                },
                "theme_mode": {
                    "type": "string",
                    "enum": [
                        "light",
                        "dark",
                        "system"
                    ]
                },
                "track_visible": {
                    "type": "boolean"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.SettingsResponse": {
            "type": "object",
            "properties": {
                "settings": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.Settings"
                }
            }
        },
        "hackathon_internal_handler_schema_response.TrackDetailItem": {
            "type": "object",
            "properties": {
                "album_name": {
                    "type": "string"
                },
                "artist_name": {
                    "type": "string"
                },
                "artwork_url": {
                    "type": "string"
                },
                "duration_ms": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "preview_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.TrackDetailResponse": {
            "type": "object",
            "properties": {
                "track": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.TrackDetailItem"
                }
            }
        },
        "hackathon_internal_handler_schema_response.TrackItem": {
            "type": "object",
            "properties": {
                "artist_name": {
                    "type": "string"
                },
                "artwork_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "preview_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.TrackSearchResponse": {
            "type": "object",
            "properties": {
                "pagination": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.PaginationResult"
                },
                "tracks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/hackathon_internal_handler_schema_response.TrackItem"
                    }
                }
            }
        },
        "hackathon_internal_handler_schema_response.User": {
            "type": "object",
            "properties": {
                "age_visibility": {
                    "type": "string",
                    "enum": [
                        "hidden",
                        "exact",
                        "by-10"
                    ]
                },
                "avatar_url": {
                    "type": "string"
                },
                "bio": {
                    "type": "string"
                },
                "birthdate": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "prefecture_id": {
                    "type": "string"
                },
                "sex": {
                    "type": "string",
                    "enum": [
                        "male",
                        "female",
                        "other",
                        "no-answer"
                    ]
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.UserBrief": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "display_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "hackathon_internal_handler_schema_response.UserResponse": {
            "type": "object",
            "properties": {
                "user": {
                    "$ref": "#/definitions/hackathon_internal_handler_schema_response.User"
                }
            }
        },
        "internal_handler.errorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_handler.errorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/internal_handler.errorBody"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Firebase ID トークン。\"Bearer \u003ctoken\u003e\" の形式で渡す。",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MusicSwapping API",
	Description:      "MusicSwapping バックエンド API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
